service: serverless-flask-call-endpoint

plugins:
  - serverless-python-requirements
  - serverless-ssm-fetch
custom:
  serverlessSsmFetch:
    ENDPOINT_NAME: /am-i-funny/endpoint-name

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1

functions:
  callEndpointLambda:
    handler: lambda_handler.lambda_handler
    ssmToEnvironment:
    - ENDPOINT_NAME
    events:
      - http:
          path: '/'
          method: POST
          cors: true