service: feedback

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30 # 30 seconds is the maximal allowed by API Gateway
  stage: ${opt:stage}
  region: 'eu-west-1'
  memorySize: 128
  environment:
    NODE_ENV: production

functions:
  saveFeedback:
    handler: saveFeedback.handler
    events:
      - http:
          path: /feedback/save
          method: POST
          cors:
            allowedOrigins:
              - https://localhost:3000
              - https://test.amifunny.co
              - https://amifunny.co
